### ISSUE TITLE
TypeError: Object true has no method 'replace'

### ISSUE THREAD

**Issue by corydorning** [klei/gulp-inject#131]
I have the following code:

```
var gulp = require('gulp')
  , _gulp = require('gulp-load-plugins')()
;
return gulp.src(paths.app.html.index)
        .pipe(
          _gulp.inject(
            gulp.src(appSources)
              .pipe(_gulp.angularFilesort())
            , {
              name: 'app',
              addRootSlash: false,
              ignorePath: 'www'
            }
          )
        )
        .pipe(gulp.dest(paths.root.www))
      ;
    })
```

Which is generating this error:
```
[16:40:01] TypeError: Object true has no method 'replace'
    at unixify (C:\web\www\gitlab\gxl-boilerplate-ng\node_modules\gulp-inject\src\inject\index.js:252:19)
    at Array.map (native)
    at Object.module.exports.exports (C:\web\www\gitlab\gxl-boilerplate-ng\node_modules\gulp-inject\src\inject\index.js:46:44)
    at Gulp.<anonymous> (C:\web\www\gitlab\gxl-boilerplate-ng\.build\tasks\html.js:11:17)
    at module.exports (C:\web\www\gitlab\gxl-boilerplate-ng\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\web\www\gitlab\gxl-boilerplate-ng\node_modules\gulp\node_modules\orchestrator\index.js:273:3
)
    at Gulp.Orchestrator._runStep (C:\web\www\gitlab\gxl-boilerplate-ng\node_modules\gulp\node_modules\orchestrator\index.js:214:1
0)
    at Gulp.Orchestrator.start (C:\web\www\gitlab\gxl-boilerplate-ng\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at runNextSet (C:\web\www\gitlab\gxl-boilerplate-ng\node_modules\run-sequence\index.js:79:16)
    at runSequence (C:\web\www\gitlab\gxl-boilerplate-ng\node_modules\run-sequence\index.js:90:2)
```

**Comment by corydorning** [comment]
Disregard. a restart of WebStorm fixed the issue.
