### ISSUE TITLE
SyntaxError: Unexpected token - creating dictionary, Failed to run Gulpfile.js

### ISSUE THREAD

**Issue by robajz** [klei/gulp-inject#179]
In VS 2015, "gulp": "3.9.1",  "gulp-inject": "4.0.0",

```
cmd.exe /c gulp --tasks-simple
myproject\node_modules\gulp-inject\src\inject\index.js:127
      startTag
             ^
SyntaxError: Unexpected token (
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (myproject\node_modules\gulp-inject\index.js:4:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

```
content = inject(content, {
      startTag,
      endTag,
      ...
```

**Comment by robajz** [comment]
Duplicate of #171
