### ISSUE TITLE
Node 4 support dropped in latest patch version?

### ISSUE THREAD

**Issue by theGrue** [klei/gulp-inject#247]
I realize Node 4 is no longer supported, but for those of us who are stuck with it, the new 4.3.3 version is no longer usable. This seems to be like something warranting a major version bump, since anyone using Node 4 pointed to `"gulp-inject": "~4.3.2"` or `"gulp-inject": "^4.3.2"` will now get 4.3.3 and fail on a syntax error.

Here's the error Node 4 users will see:

```
/src/node_modules/gulp-inject/node_modules/ansi-colors/index.js:17
  let { open, close, regex } = style;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/src/node_modules/gulp-inject/src/inject/index.js:5:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by rejas** [comment]
you're right @theGrue 
@joakimbeng maybe we should re-release this new version as v5 and retract the 4.3.3 release?

**Comment by joakimbeng** [comment]
Aha, didn't know that!
@rejas yes, that sounds like a good idea! To get the new correct there should be a commit with a "BREAKING CHANGE:" as a footer in the commit message

**Comment by rejas** [comment]
thx for the hint @joakimbeng pushed a commit with some breaking changes ;-)

**Comment by joakimbeng** [comment]
Version v4.3.3 has been unpublished

**Comment by joakimbeng** [comment]
And v5.0.0 is soon released (when the builds succeed). Closing...
